# Generated by Django 2.0.7 on 2018-07-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='django_url',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener.DjangoURL'),
        ),
    ]
